In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [2]:
X=np.array([
    [0.,0.],
    [0.,1.],
    [1.,0.],
    [1.,1.]
],dtype="float32")

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y=np.array([0,0,0,1],dtype="int32")

In [5]:
y

array([0, 0, 0, 1])

In [6]:
model=Sequential()
model.add(Dense(1,input_dim=2,activation="sigmoid"))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss='binary_crossentropy',optimizer=Adam(lr=0.1),metrics=['acc'])

In [12]:
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 0.7789 - acc: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 0.7470 - acc: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 0.7161 - acc: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 0.6863 - acc: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6577 - acc: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 0.6302 - acc: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 0.6040 - acc: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5789 - acc: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5551 - acc: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5324 - acc: 0.7500
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5109 -

In [13]:
pred=model.predict(X)

1/1 [==============================] - 0s 47ms/step


In [14]:
pred

array([[0.00135916],
       [0.08696259],
       [0.09343671],
       [0.87823844]], dtype=float32)

In [15]:
predict01=np.where(pred>0.5,1,0)
print("===========================================")
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [0]
 [1]]


In [16]:
predict02=predict01.flatten()

In [17]:
predict02

array([0, 0, 0, 1])

In [18]:
predict03=(predict02==y)

In [19]:
predict03

array([ True,  True,  True,  True])

In [20]:
np.sum(predict03)

4

In [21]:
acc=np.sum(predict03)/4

In [22]:
acc

1.0

In [23]:
arr=np.array([[0,1]],dtype="float32")
pred=model.predict(arr)
pred

1/1 [==============================] - 0s 13ms/step


array([[0.08696259]], dtype=float32)

In [24]:
predict01=np.where(pred>0.5,1,0)
print("=======================================")
print("predict01")
print(predict01)

predict01
[[0]]


In [25]:
arr=np.array([[1,1]],dtype="float32")
pred=model.predict(arr)
pred

1/1 [==============================] - 0s 15ms/step


array([[0.87823844]], dtype=float32)

In [26]:
predict01=np.where(pred>0.5,1,0)
print("==================================")
print("predict01")
print(predict01)

predict01
[[1]]
