In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [2]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
],dtype="float32")
y=np.array([0,1,1,0],dtype="float32")

In [3]:
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)

In [4]:
y

array([0., 1., 1., 0.], dtype=float32)

In [5]:
model=Sequential()

In [6]:
model.add(Dense(10,input_dim=2,activation="sigmoid"))

In [7]:
model.add(Dense(1,activation="sigmoid"))

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 1)                 11        
                                                                 
Total params: 41
Trainable params: 41
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(loss='binary_crossentropy',optimizer=Adam(lr=0.01),metrics=['acc'])

C:\Users\User\anaconda3\envs\tensorflow_env01\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [11]:
model.fit(X,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 0.7493 - acc: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7373 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7267 - acc: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7176 - acc: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7100 - acc: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7040 - acc: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6995 - acc: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 9ms/step - loss: 0.6963 - acc: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6943 - acc: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6935 - acc: 0.5000
Epoch 11/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6934 

In [12]:
pred=model.predict(X)
pred

1/1 [==============================] - 0s 53ms/step


array([[0.00945789],
       [0.97692955],
       [0.9788759 ],
       [0.03020553]], dtype=float32)

In [13]:
predict01=np.where(pred>0.5,1,0)
print("================================================")
print("predict01")
print(predict01)

predict01
[[0]
 [1]
 [1]
 [0]]


In [14]:
predict02=predict01.flatten()
predict02

array([0, 1, 1, 0])

In [15]:
predict03=(predict02==y)
predict03

array([ True,  True,  True,  True])

In [16]:
np.sum(predict03)

4

In [17]:
acc=np.sum(predict03)/len(predict03)
acc

1.0

In [18]:
arr=np.array([[0,1]],dtype="float32")
pred=model.predict(arr)
pred

1/1 [==============================] - 0s 14ms/step


array([[0.97692955]], dtype=float32)

In [19]:
predict01=np.where(pred>0.5,1,0)
print("=================================================")
print("predict01")
print(predict01)

predict01
[[1]]


In [20]:
arr=np.array([[1,1]],dtype="float32")
pred=model.predict(arr)
pred

1/1 [==============================] - 0s 13ms/step


array([[0.03020553]], dtype=float32)

In [21]:
predict01=np.where(pred>0.5,1,0)
print("=========================================")
print("predict01")
print(predict01)

predict01
[[0]]
