In [1]:
!conda install scikit-learn -y

Channels:
 - defaults
 - nvidia
 - pytorch
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [2]:
!conda install pandas -y

Channels:
 - defaults
 - nvidia
 - pytorch
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import torch
import torch.optim as optim
import torch.nn as nn
import random

In [4]:
random_seed=178
torch.manual_seed(random_seed)
torch.backends.cudnn.deterministic=True
torch.backends.cudnn.benchmark=False
np.random.seed(random_seed)

In [5]:
data=datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
X=data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [7]:
y=data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [8]:
y=y.reshape(-1,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=157)

In [10]:
X_train

array([[1.861e+01, 2.025e+01, 1.221e+02, ..., 1.490e-01, 2.341e-01,
        7.421e-02],
       [1.025e+01, 1.618e+01, 6.652e+01, ..., 9.744e-02, 2.608e-01,
        9.702e-02],
       [1.808e+01, 2.184e+01, 1.174e+02, ..., 9.181e-02, 2.369e-01,
        6.558e-02],
       ...,
       [1.149e+01, 1.459e+01, 7.399e+01, ..., 7.431e-02, 2.941e-01,
        9.180e-02],
       [9.465e+00, 2.101e+01, 6.011e+01, ..., 6.517e-02, 2.878e-01,
        9.211e-02],
       [2.092e+01, 2.509e+01, 1.430e+02, ..., 2.542e-01, 2.929e-01,
        9.873e-02]])

In [11]:
X_test

array([[1.646e+01, 2.011e+01, 1.093e+02, ..., 2.035e-01, 3.054e-01,
        9.519e-02],
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.029e+01, 2.761e+01, 6.567e+01, ..., 9.127e-02, 2.226e-01,
        8.283e-02],
       ...,
       [1.420e+01, 2.053e+01, 9.241e+01, ..., 1.339e-01, 2.534e-01,
        7.858e-02],
       [1.234e+01, 1.495e+01, 7.829e+01, ..., 4.793e-02, 2.298e-01,
        5.974e-02],
       [1.534e+01, 1.426e+01, 1.025e+02, ..., 2.393e-01, 4.667e-01,
        9.946e-02]])

In [12]:
y_train

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
    

In [13]:
y_test

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [15]:
X_train=scaler.transform(X_train)
X_train

array([[ 1.29107843,  0.21655526,  1.25811822, ...,  0.55886851,
        -0.90904397, -0.55448318],
       [-1.083668  , -0.71213691, -1.03183658, ..., -0.24022995,
        -0.47282394,  0.7570558 ],
       [ 1.14052632,  0.57936128,  1.06447325, ..., -0.32748605,
        -0.86329805, -1.05069455],
       ...,
       [-0.73143289, -1.07494294, -0.72406468, ..., -0.59870838,
         0.07122575,  0.45691405],
       [-1.30665556,  0.38997197, -1.29593536, ..., -0.74036392,
        -0.03170257,  0.47473856],
       [ 1.94725836,  1.32094593,  2.11922034, ...,  2.18930216,
         0.05162036,  0.8553781 ]])

In [16]:
X_test=scaler.transform(X_test)
X_test

array([[ 0.68034818,  0.18461007,  0.73074468, ...,  1.40353233,
         0.25584322,  0.65183369],
       [-0.18035537,  0.07508372, -0.23583214, ...,  0.0474207 ,
        -0.02189987, -0.58323239],
       [-1.07230558,  1.89595926, -1.06685748, ..., -0.33585519,
        -1.096929  , -0.05884679],
       ...,
       [ 0.03837128,  0.28044562,  0.03485881, ...,  0.32484239,
        -0.59372387, -0.30321508],
       [-0.4899814 , -0.99279817, -0.54690013, ..., -1.00755666,
        -0.97929663, -1.38648533],
       [ 0.36220034, -1.1502423 ,  0.45057749, ...,  1.95837572,
         2.89113498,  0.89735195]])

In [17]:
X_train=torch.FloatTensor(X_train)
X_train

tensor([[ 1.2911,  0.2166,  1.2581,  ...,  0.5589, -0.9090, -0.5545],
        [-1.0837, -0.7121, -1.0318,  ..., -0.2402, -0.4728,  0.7571],
        [ 1.1405,  0.5794,  1.0645,  ..., -0.3275, -0.8633, -1.0507],
        ...,
        [-0.7314, -1.0749, -0.7241,  ..., -0.5987,  0.0712,  0.4569],
        [-1.3067,  0.3900, -1.2959,  ..., -0.7404, -0.0317,  0.4747],
        [ 1.9473,  1.3209,  2.1192,  ...,  2.1893,  0.0516,  0.8554]])

In [18]:
X_test=torch.FloatTensor(X_test)
X_test

tensor([[ 0.6803,  0.1846,  0.7307,  ...,  1.4035,  0.2558,  0.6518],
        [-0.1804,  0.0751, -0.2358,  ...,  0.0474, -0.0219, -0.5832],
        [-1.0723,  1.8960, -1.0669,  ..., -0.3359, -1.0969, -0.0588],
        ...,
        [ 0.0384,  0.2804,  0.0349,  ...,  0.3248, -0.5937, -0.3032],
        [-0.4900, -0.9928, -0.5469,  ..., -1.0076, -0.9793, -1.3865],
        [ 0.3622, -1.1502,  0.4506,  ...,  1.9584,  2.8911,  0.8974]])

In [19]:
y_train=torch.FloatTensor(y_train)
y_train

tensor([[0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
      

In [20]:
y_test=torch.FloatTensor(y_test)
y_test

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [21]:
mlp_model=nn.Sequential(
    nn.Linear(in_features=30,out_features=50),
    nn.Sigmoid(),
    nn.Linear(in_features=50,out_features=10),
    nn.Sigmoid(),
    nn.Linear(in_features=10,out_features=1),
    nn.Sigmoid()
)

In [22]:
mlp_model

Sequential(
  (0): Linear(in_features=30, out_features=50, bias=True)
  (1): Sigmoid()
  (2): Linear(in_features=50, out_features=10, bias=True)
  (3): Sigmoid()
  (4): Linear(in_features=10, out_features=1, bias=True)
  (5): Sigmoid()
)

In [23]:
list(mlp_model.parameters())[0]

Parameter containing:
tensor([[-0.0743, -0.0914,  0.1169,  ..., -0.1273,  0.1368,  0.0223],
        [-0.1395, -0.0347,  0.0080,  ...,  0.0443,  0.1441,  0.1359],
        [-0.1666,  0.1298, -0.1268,  ...,  0.0280,  0.0306,  0.0187],
        ...,
        [-0.1285,  0.1750,  0.1702,  ...,  0.1499, -0.1746, -0.0020],
        [ 0.1011, -0.0967,  0.0444,  ...,  0.0658,  0.1573, -0.0457],
        [-0.0584,  0.1413, -0.0537,  ..., -0.1238, -0.1446,  0.1756]],
       requires_grad=True)

In [24]:
list(mlp_model.parameters())[1]

Parameter containing:
tensor([-0.1144,  0.0781, -0.1608, -0.0793, -0.0995, -0.0719,  0.0670, -0.1286,
        -0.0997,  0.1387,  0.1685, -0.1619, -0.0905,  0.0997, -0.0503,  0.0962,
        -0.1161, -0.0699, -0.0729,  0.1148, -0.1310,  0.1152, -0.0608, -0.1320,
         0.1317, -0.0771, -0.1156, -0.1167, -0.0413,  0.1589,  0.0693, -0.1234,
        -0.1801,  0.1768,  0.1022,  0.0141, -0.1473, -0.0246, -0.1474, -0.1609,
         0.0672, -0.1361, -0.0749, -0.1046,  0.0725, -0.0995, -0.0338,  0.1742,
         0.1517,  0.0560], requires_grad=True)

In [25]:
list(mlp_model.parameters())[2]

Parameter containing:
tensor([[ 9.8587e-02,  3.1380e-02, -8.9836e-02,  7.7349e-02, -9.2033e-03,
          1.3811e-01, -1.1440e-01,  8.0005e-02,  9.2054e-02, -3.9064e-02,
          6.9505e-02,  6.6289e-02,  3.8774e-02, -7.6143e-03,  4.3547e-03,
          1.1850e-01,  1.3103e-01, -7.4806e-02, -5.1079e-03,  4.9212e-02,
         -1.1945e-01, -5.7207e-02,  3.5848e-02,  9.1817e-02, -9.9158e-02,
         -1.4992e-02, -6.0759e-02, -8.1960e-02, -4.2812e-02,  7.1178e-02,
          1.1827e-01, -4.7064e-02, -1.1398e-01, -1.0267e-02, -7.9485e-02,
          9.1783e-02,  1.6402e-02, -7.1961e-02,  7.1142e-02,  1.3409e-01,
          1.1563e-02,  7.1601e-02, -1.2199e-01,  4.4058e-02, -6.5952e-02,
         -6.3197e-02, -3.9838e-02, -5.0752e-02, -7.8047e-02, -1.4098e-01],
        [ 1.1216e-01,  1.2437e-01,  1.3114e-01,  3.6845e-02, -1.0608e-01,
         -9.6866e-02,  1.2114e-01, -1.1678e-01, -9.5857e-02, -5.0425e-02,
          3.4141e-02, -6.6541e-02,  7.2841e-02,  2.5089e-02,  2.9786e-02,
          4.839

In [26]:
list(mlp_model.parameters())[3]

Parameter containing:
tensor([ 0.0420, -0.0104,  0.0637, -0.0273, -0.0659,  0.0481,  0.0994, -0.0115,
        -0.0717,  0.0543], requires_grad=True)

In [27]:
list(mlp_model.parameters())[4]

Parameter containing:
tensor([[-0.0139,  0.2667, -0.3123, -0.0554, -0.1858,  0.2770,  0.1246, -0.2940,
         -0.0533,  0.0574]], requires_grad=True)

In [28]:
list(mlp_model.parameters())[5]

Parameter containing:
tensor([0.2614], requires_grad=True)

In [29]:
optimizer=optim.Adam(mlp_model.parameters(),lr=0.01)

In [30]:
for i in range(1000):
    print("i=",i)
    hypothesis=mlp_model(X_train)
    print("hypothesis[:3]=",hypothesis[:3])
    cost=torch.mean(-y_train*torch.log(hypothesis)-(1-y_train)*torch.log(1-hypothesis))
    print("cost=",cost)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print("="*100)

i= 0
hypothesis[:3]= tensor([[0.5498],
        [0.5486],
        [0.5506]], grad_fn=<SliceBackward0>)
cost= tensor(0.6697, grad_fn=<MeanBackward0>)
i= 1
hypothesis[:3]= tensor([[0.5797],
        [0.5870],
        [0.5829]], grad_fn=<SliceBackward0>)
cost= tensor(0.6483, grad_fn=<MeanBackward0>)
i= 2
hypothesis[:3]= tensor([[0.6032],
        [0.6200],
        [0.6090]], grad_fn=<SliceBackward0>)
cost= tensor(0.6319, grad_fn=<MeanBackward0>)
i= 3
hypothesis[:3]= tensor([[0.6200],
        [0.6475],
        [0.6289]], grad_fn=<SliceBackward0>)
cost= tensor(0.6176, grad_fn=<MeanBackward0>)
i= 4
hypothesis[:3]= tensor([[0.6302],
        [0.6700],
        [0.6428]], grad_fn=<SliceBackward0>)
cost= tensor(0.6035, grad_fn=<MeanBackward0>)
i= 5
hypothesis[:3]= tensor([[0.6341],
        [0.6884],
        [0.6514]], grad_fn=<SliceBackward0>)
cost= tensor(0.5882, grad_fn=<MeanBackward0>)
i= 6
hypothesis[:3]= tensor([[0.6322],
        [0.7038],
        [0.6554]], grad_fn=<SliceBackward0>)
cost= tens

In [31]:
list(mlp_model.parameters())[0]

Parameter containing:
tensor([[-0.1923, -0.2120, -0.0030,  ..., -0.5909, -0.2811, -0.4057],
        [-0.2565, -0.2772, -0.0939,  ...,  0.4769,  0.1404,  0.8675],
        [-0.1942,  0.1050, -0.1587,  ..., -0.6119, -0.3753, -0.3921],
        ...,
        [-0.5512,  0.0185, -0.2155,  ..., -0.5697, -1.2091,  0.1962],
        [-0.0796, -0.2822, -0.1391,  ..., -0.4322,  0.0060, -0.4162],
        [-0.1818, -0.1440, -0.1631,  ..., -0.5914, -0.9822,  0.5116]],
       requires_grad=True)

In [32]:
list(mlp_model.parameters())[1]

Parameter containing:
tensor([-0.4889,  0.1117, -0.7994, -0.8015, -0.8124,  0.4574, -0.5579, -0.8480,
        -0.5661, -0.3735, -0.8043, -0.5865,  0.5128, -2.3069, -0.3361,  0.6248,
        -0.6646, -0.6886,  0.6778,  0.5377,  0.4387, -0.3897, -0.6734, -0.4053,
        -0.4174, -0.4219,  0.4933,  0.2915, -0.7270, -0.2754, -1.3525, -0.5920,
        -0.7358, -0.3545, -0.5018,  0.6902, -0.5939, -0.6965, -0.8999,  0.5641,
        -0.3778, -2.6965, -2.7392, -0.2020, -0.5945, -0.9164, -1.3240,  0.1753,
        -0.4396,  0.8060], requires_grad=True)

In [33]:
list(mlp_model.parameters())[2]

Parameter containing:
tensor([[ 0.7494, -1.3839,  0.6332,  0.9854,  0.9486, -0.5918,  0.6342, -0.8730,
         -0.8170,  0.6760, -0.8529, -0.8463, -0.7033, -2.4606,  0.6805, -0.7642,
         -1.9399,  0.7654, -0.8203, -0.7235,  1.5464, -0.9502, -0.7362, -0.9176,
          0.7615,  0.7485, -0.8094, -0.7526,  0.7140,  0.8998,  1.0535, -0.9522,
          1.0025,  0.7327,  0.4946,  1.1940,  1.0445, -0.8457,  0.9579,  1.3396,
          0.8102, -2.4019, -2.7482, -2.1422,  0.7127,  0.7373,  1.1025,  1.6048,
          0.7576,  0.6527],
        [ 0.3951, -0.5959,  0.4440,  0.3969,  0.5480, -0.3945,  0.4870, -0.4408,
         -0.4709,  0.2538, -0.3653, -0.4448, -0.3563, -1.1829,  0.3272, -0.2407,
         -0.9006,  0.3975, -0.4568, -0.4084,  0.6639, -0.3878, -0.3562, -0.4239,
          0.6313,  0.4209, -0.4132, -0.4696,  0.3843,  0.0847,  0.4895, -0.3910,
          0.7413,  0.4062,  0.4091,  0.4965,  0.6370, -0.4980,  0.3527,  0.5675,
          0.4126, -1.0667, -1.2349, -1.0283,  0.4283,  0.28

In [34]:
list(mlp_model.parameters())[3]

Parameter containing:
tensor([ 0.1782, -0.2689,  0.2992,  0.5073,  0.2292, -0.2334, -0.2279,  0.2429,
         0.2804, -0.2876], requires_grad=True)

In [35]:
list(mlp_model.parameters())[4]

Parameter containing:
tensor([[ 1.5509,  1.5747, -1.4622, -1.4903, -1.3819,  1.6420,  1.5605, -1.4491,
         -1.3131,  1.4964]], requires_grad=True)

In [36]:
list(mlp_model.parameters())[5]

Parameter containing:
tensor([-0.0376], requires_grad=True)

In [37]:
predict=mlp_model(X_test)
predict

tensor([[8.0584e-04],
        [7.9705e-04],
        [9.9958e-01],
        [9.9956e-01],
        [7.9683e-04],
        [9.9941e-01],
        [7.9804e-04],
        [7.9700e-04],
        [7.9685e-04],
        [9.9958e-01],
        [9.9958e-01],
        [9.9958e-01],
        [9.9956e-01],
        [8.4214e-04],
        [4.1067e-02],
        [7.9876e-04],
        [7.9679e-04],
        [9.9958e-01],
        [8.3052e-04],
        [9.9959e-01],
        [9.5433e-02],
        [9.9958e-01],
        [9.9958e-01],
        [9.9958e-01],
        [9.9958e-01],
        [9.9958e-01],
        [7.9693e-04],
        [8.7436e-04],
        [7.9944e-04],
        [9.9958e-01],
        [9.9958e-01],
        [7.9684e-04],
        [7.9701e-04],
        [9.9946e-01],
        [7.9823e-04],
        [7.9754e-04],
        [7.9693e-04],
        [9.9958e-01],
        [9.9958e-01],
        [9.9958e-01],
        [7.9746e-04],
        [7.9961e-04],
        [9.9958e-01],
        [9.9958e-01],
        [7.9703e-04],
        [9

In [38]:
predict01=torch.where(predict>=0.5,torch.tensor([1.]),torch.tensor([0.]))
predict01

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [39]:
y_test

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [40]:
predict01.eq(y_test)

tensor([[ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True

In [41]:
acc01=predict01.eq(y_test)
acc01

tensor([[ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True

In [42]:
acc01.type(torch.DoubleTensor)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [43]:
acc02=acc01.type(torch.DoubleTensor)
acc02

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [44]:
acc03=torch.mean(acc02)
acc03

tensor(0.9737, dtype=torch.float64)

In [45]:
X_arr=np.array([
    [3.8312,1.6324,3.9907,5.4532,0.8753,1.8759,3.5362,3.1806,0.8990,-0.9087,7.9715,0.1713,8.0943,11.9829,0.2529,1.6661,1.5853,2.3802,-0.4427,0.3207,4.1694,0.9339,4.3981,6.2228,0.1643,1.1448,1.9777,2.2735,-0.4414,-0.5454]
])

In [46]:
X_arr

array([[ 3.8312,  1.6324,  3.9907,  5.4532,  0.8753,  1.8759,  3.5362,
         3.1806,  0.899 , -0.9087,  7.9715,  0.1713,  8.0943, 11.9829,
         0.2529,  1.6661,  1.5853,  2.3802, -0.4427,  0.3207,  4.1694,
         0.9339,  4.3981,  6.2228,  0.1643,  1.1448,  1.9777,  2.2735,
        -0.4414, -0.5454]])

In [47]:
X_arr=scaler.transform(X_arr)
X_arr

array([[  -2.90699604,   -4.03160671,   -3.6081099 ,   -1.83387144,
          55.18484158,   33.70478084,   43.24791897,   81.50472528,
          25.63391221, -134.80283957,   26.86187931,   -1.97667187,
           2.51847005,   -0.59238962,   80.29196247,   92.02969909,
          49.68047742,  372.61024779,  -55.31157629,  115.62630787,
          -2.48112343,   -4.00363887,   -3.03064892,   -1.50876147,
           1.4438789 ,    5.92634966,    8.28596168,   33.48525897,
         -11.94524722,  -36.18107986]])

In [48]:
X_arr=torch.FloatTensor(X_arr)
X_arr

tensor([[  -2.9070,   -4.0316,   -3.6081,   -1.8339,   55.1848,   33.7048,
           43.2479,   81.5047,   25.6339, -134.8028,   26.8619,   -1.9767,
            2.5185,   -0.5924,   80.2920,   92.0297,   49.6805,  372.6103,
          -55.3116,  115.6263,   -2.4811,   -4.0036,   -3.0306,   -1.5088,
            1.4439,    5.9263,    8.2860,   33.4853,  -11.9452,  -36.1811]])

In [49]:
predict=mlp_model(X_arr)

In [50]:
predict

tensor([[0.0038]], grad_fn=<SigmoidBackward0>)