In [1]:
!conda install scikit-learn -y

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [2]:
!conda install pandas -y

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [4]:
data=datasets.load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [5]:
X=data.data
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [6]:
y=data.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
y=y.reshape(-1,1)
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=157)

In [9]:
X_train

array([[1.861e+01, 2.025e+01, 1.221e+02, ..., 1.490e-01, 2.341e-01,
        7.421e-02],
       [1.025e+01, 1.618e+01, 6.652e+01, ..., 9.744e-02, 2.608e-01,
        9.702e-02],
       [1.808e+01, 2.184e+01, 1.174e+02, ..., 9.181e-02, 2.369e-01,
        6.558e-02],
       ...,
       [1.149e+01, 1.459e+01, 7.399e+01, ..., 7.431e-02, 2.941e-01,
        9.180e-02],
       [9.465e+00, 2.101e+01, 6.011e+01, ..., 6.517e-02, 2.878e-01,
        9.211e-02],
       [2.092e+01, 2.509e+01, 1.430e+02, ..., 2.542e-01, 2.929e-01,
        9.873e-02]])

In [10]:
X_test

array([[1.646e+01, 2.011e+01, 1.093e+02, ..., 2.035e-01, 3.054e-01,
        9.519e-02],
       [1.343e+01, 1.963e+01, 8.584e+01, ..., 1.160e-01, 2.884e-01,
        7.371e-02],
       [1.029e+01, 2.761e+01, 6.567e+01, ..., 9.127e-02, 2.226e-01,
        8.283e-02],
       ...,
       [1.420e+01, 2.053e+01, 9.241e+01, ..., 1.339e-01, 2.534e-01,
        7.858e-02],
       [1.234e+01, 1.495e+01, 7.829e+01, ..., 4.793e-02, 2.298e-01,
        5.974e-02],
       [1.534e+01, 1.426e+01, 1.025e+02, ..., 2.393e-01, 4.667e-01,
        9.946e-02]])

In [11]:
y_train

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
    

In [12]:
y_test

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [14]:
X_train=scaler.transform(X_train)
X_train

array([[ 1.29107843,  0.21655526,  1.25811822, ...,  0.55886851,
        -0.90904397, -0.55448318],
       [-1.083668  , -0.71213691, -1.03183658, ..., -0.24022995,
        -0.47282394,  0.7570558 ],
       [ 1.14052632,  0.57936128,  1.06447325, ..., -0.32748605,
        -0.86329805, -1.05069455],
       ...,
       [-0.73143289, -1.07494294, -0.72406468, ..., -0.59870838,
         0.07122575,  0.45691405],
       [-1.30665556,  0.38997197, -1.29593536, ..., -0.74036392,
        -0.03170257,  0.47473856],
       [ 1.94725836,  1.32094593,  2.11922034, ...,  2.18930216,
         0.05162036,  0.8553781 ]])

In [15]:
X_test=scaler.transform(X_test)
X_test

array([[ 0.68034818,  0.18461007,  0.73074468, ...,  1.40353233,
         0.25584322,  0.65183369],
       [-0.18035537,  0.07508372, -0.23583214, ...,  0.0474207 ,
        -0.02189987, -0.58323239],
       [-1.07230558,  1.89595926, -1.06685748, ..., -0.33585519,
        -1.096929  , -0.05884679],
       ...,
       [ 0.03837128,  0.28044562,  0.03485881, ...,  0.32484239,
        -0.59372387, -0.30321508],
       [-0.4899814 , -0.99279817, -0.54690013, ..., -1.00755666,
        -0.97929663, -1.38648533],
       [ 0.36220034, -1.1502423 ,  0.45057749, ...,  1.95837572,
         2.89113498,  0.89735195]])

In [16]:
model=Sequential()

In [17]:
model.add(Dense(50,input_dim=30,activation="sigmoid"))

In [18]:
model.add(Dense(10,activation="sigmoid"))

In [19]:
model.add(Dense(1,activation="sigmoid"))

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                1550      
                                                                 
 dense_1 (Dense)             (None, 10)                510       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 2,071
Trainable params: 2,071
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.compile(loss='binary_crossentropy',optimizer=Adam(lr=0.001),metrics=['acc'])

C:\Users\User\anaconda3\envs\tensorflow_env01\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [22]:
model.fit(X_train,y_train,epochs=1000)

Epoch 1/1000
15/15 [==============================] - 1s 2ms/step - loss: 0.6131 - acc: 0.6440
Epoch 2/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.5651 - acc: 0.6462
Epoch 3/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.5185 - acc: 0.7121
Epoch 4/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.4731 - acc: 0.8220
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.4299 - acc: 0.8813
Epoch 6/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.3894 - acc: 0.9143
Epoch 7/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.3537 - acc: 0.9275
Epoch 8/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.3226 - acc: 0.9363
Epoch 9/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.2953 - acc: 0.9473
Epoch 10/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.2717 - acc: 0.9516
Epoch 11/1000
15/15 [============================

In [23]:
pred=model.predict(X_test)
pred

4/4 [==============================] - 0s 1000us/step


array([[6.1869623e-06],
       [6.0405546e-06],
       [9.9999857e-01],
       [9.9999821e-01],
       [6.0384518e-06],
       [9.9999774e-01],
       [6.0710413e-06],
       [6.0493453e-06],
       [6.0390566e-06],
       [9.9999833e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999666e-01],
       [6.1471110e-06],
       [3.8458601e-02],
       [6.0464786e-06],
       [6.0378129e-06],
       [9.9999857e-01],
       [6.1439573e-06],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [6.0385728e-06],
       [7.8387413e-05],
       [6.0407096e-06],
       [9.9999857e-01],
       [9.9999857e-01],
       [6.0386128e-06],
       [6.0390048e-06],
       [9.9998963e-01],
       [6.1025903e-06],
       [6.0414873e-06],
       [6.0381813e-06],
       [9.9999857e-01],
       [9.9999857e-01],
       [9.9999857e-01],
       [6.0768571e-06],
       [6.044138

In [24]:
predict01=np.where(pred>0.5,1,0)
print("==========================================")
print("predict01")
print(predict01)

predict01
[[0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]]


In [25]:
predict02=predict01.flatten()
predict02

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0])

In [26]:
predict03=(predict02==y_test.flatten())
predict03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [27]:
np.sum(predict03)

110

In [28]:
acc=np.sum(predict03)/len(predict03)
acc

0.9649122807017544