In [1]:
!conda install scikit-learn -y

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\User\anaconda3\envs\tensorflow_env01

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    intel-openmp-2023.1.0      |   h59b6b97_46320         2.7 MB
    mkl-2023.1.0               |   h6b88ed4_46358       155.9 MB
    mkl-service-2.4.0          |  py310h2bbff1b_1          44 KB
    mkl_fft-1.3.10             |  py310h827c3e9_0         181 KB
    mkl_random-1.2.7           |  py310hc64d2fc_0         281 KB
    numpy-1.26.4               |  py310h055cbcc_0          11 KB
    numpy-base-1.26.4          |  py310h65a83cf_0         8.6 MB
    pybind11-abi-5             |       hd3eb1b0_0          14 KB
    scipy-1.13.1               |  py310h8640f81_0        25.4 MB
    tbb-2021.8.0               |       h59b6b97_0     

In [2]:
!conda install pandas -y

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\User\anaconda3\envs\tensorflow_env01

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numexpr-2.8.7              |  py310h2cd9be0_0         134 KB
    ------------------------------------------------------------
                                           Total:         134 KB

The following NEW packages will be INSTALLED:

  bottleneck         pkgs/main/win-64::bottleneck-1.3.7-py310h9128911_0 
  numexpr            pkgs/main/win-64::numexpr-2.8.7-py310h2cd9be0_0 
  pandas             pkgs/main/win-64::pandas-2.2.2-py310h5da7b33_0 
  python-dateutil    pkgs/main/win-64::python-dateutil-2.9.0post0-py310haa95532_2 
  python-tzdata      pkgs/main/noarch::python-tzdata-2023.3-pyhd3eb1b0_0 
  pytz               pkgs/main/wi

In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import tensorflow as tf

In [4]:
data=datasets.load_breast_cancer()

In [5]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
X=data.data

In [7]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
y=data.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [11]:
X_train

array([[9.720e+00, 1.822e+01, 6.073e+01, ..., 0.000e+00, 1.909e-01,
        6.559e-02],
       [1.785e+01, 1.323e+01, 1.146e+02, ..., 8.341e-02, 1.783e-01,
        5.871e-02],
       [1.075e+01, 1.497e+01, 6.826e+01, ..., 3.413e-02, 2.300e-01,
        6.769e-02],
       ...,
       [2.171e+01, 1.725e+01, 1.409e+02, ..., 1.820e-01, 2.510e-01,
        6.494e-02],
       [1.866e+01, 1.712e+01, 1.214e+02, ..., 1.674e-01, 2.894e-01,
        8.456e-02],
       [1.206e+01, 1.274e+01, 7.684e+01, ..., 7.025e-02, 2.514e-01,
        7.898e-02]])

In [12]:
X_test

array([[2.031e+01, 2.706e+01, 1.329e+02, ..., 1.697e-01, 3.151e-01,
        7.999e-02],
       [1.254e+01, 1.632e+01, 8.125e+01, ..., 8.411e-02, 3.155e-01,
        7.538e-02],
       [1.262e+01, 1.715e+01, 8.062e+01, ..., 9.851e-02, 3.270e-01,
        7.330e-02],
       ...,
       [2.161e+01, 2.228e+01, 1.444e+02, ..., 2.422e-01, 3.828e-01,
        1.007e-01],
       [1.492e+01, 1.493e+01, 9.645e+01, ..., 1.147e-01, 2.688e-01,
        8.273e-02],
       [1.386e+01, 1.693e+01, 9.096e+01, ..., 1.654e-01, 3.630e-01,
        1.059e-01]])

In [13]:
y_train

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,

In [14]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0])

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler=StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [18]:
X_train=scaler.transform(X_train)

In [19]:
X_train

array([[-1.25138333, -0.26364143, -1.28213233, ..., -1.70942808,
        -1.58761209, -1.02210904],
       [ 1.02085201, -1.43788949,  0.89475336, ..., -0.46991171,
        -1.78831463, -1.41129967],
       [-0.96351095, -1.02843225, -0.97784517, ..., -1.20223837,
        -0.96479705, -0.90331539],
       ...,
       [ 2.09967469, -0.49190208,  1.95753587, ...,  0.99518743,
        -0.63029281, -1.0588785 ],
       [ 1.24723708, -0.52249371,  1.16954124, ...,  0.77822377,
        -0.01862791,  0.05099362],
       [-0.59738201, -1.55319641, -0.63112753, ..., -0.66547621,
        -0.6239213 , -0.26465808]])

In [20]:
model=Sequential()

In [21]:
model.add(Dense(1,input_dim=30,activation="sigmoid"))

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.compile(loss='binary_crossentropy',optimizer=Adam(lr=0.001),metrics=['acc'])

C:\Users\User\anaconda3\envs\tensorflow_env01\lib\site-packages\keras\optimizers\optimizer_v2\adam.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [24]:
model.fit(X_train,y_train,epochs=1000)

Epoch 1/1000
15/15 [==============================] - 1s 3ms/step - loss: 0.4937 - acc: 0.7714
Epoch 2/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.4382 - acc: 0.8220
Epoch 3/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.3936 - acc: 0.8549
Epoch 4/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.3588 - acc: 0.8747
Epoch 5/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.3310 - acc: 0.8901
Epoch 6/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.3081 - acc: 0.9011
Epoch 7/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.2890 - acc: 0.9055
Epoch 8/1000
15/15 [==============================] - 0s 3ms/step - loss: 0.2729 - acc: 0.9187
Epoch 9/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.2591 - acc: 0.9231
Epoch 10/1000
15/15 [==============================] - 0s 2ms/step - loss: 0.2467 - acc: 0.9231
Epoch 11/1000
15/15 [============================

In [25]:
X_test=scaler.transform(X_test)

In [26]:
X_test

array([[ 1.70839186,  1.8165896 ,  1.63425602, ...,  0.81240297,
         0.39074156, -0.20752399],
       [-0.4632279 , -0.71074991, -0.45291951, ..., -0.45950934,
         0.39711307, -0.46830434],
       [-0.44086888, -0.5154341 , -0.4783778 , ..., -0.24551778,
         0.58029397, -0.58596663],
       ...,
       [ 2.07172592,  0.69175879,  2.09897081, ...,  1.88979102,
         1.46911952,  0.96400769],
       [ 0.20195293, -1.03784506,  0.1613122 , ..., -0.00492589,
        -0.34676064, -0.05252656],
       [-0.09430408, -0.56720456, -0.06053859, ...,  0.74850272,
         1.15372981,  1.2581634 ]])

In [27]:
pred=model.predict(X_test)

4/4 [==============================] - 0s 1ms/step


In [28]:
pred

array([[8.94100264e-14],
       [9.99761045e-01],
       [9.99338686e-01],
       [1.00000000e+00],
       [6.29883143e-04],
       [9.99999762e-01],
       [8.64625501e-04],
       [1.82664946e-01],
       [1.71604631e-09],
       [3.43070303e-15],
       [1.25399458e-06],
       [9.99998212e-01],
       [9.99564350e-01],
       [7.13190809e-02],
       [1.40765487e-05],
       [9.99992609e-01],
       [1.00000000e+00],
       [9.99636173e-01],
       [8.20905323e-12],
       [8.70829922e-07],
       [9.99999404e-01],
       [9.99859333e-01],
       [8.74827206e-01],
       [9.94388998e-01],
       [9.50894117e-01],
       [9.99904394e-01],
       [9.99994040e-01],
       [3.68425087e-03],
       [9.29452557e-11],
       [7.05634390e-13],
       [1.15735231e-04],
       [2.50973335e-05],
       [2.23833425e-24],
       [9.93907392e-01],
       [9.99804199e-01],
       [9.99999523e-01],
       [1.03802618e-03],
       [4.08451961e-05],
       [9.99058068e-01],
       [7.36181605e-09],


In [29]:
predict01=np.where(pred>0.5,1,0)
print("========================================")
print("predict01")
print(predict01)

predict01
[[0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]]


In [30]:
predict02=predict01.flatten()

In [31]:
predict02

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1])

In [32]:
predict03=(predict02==y_test)

In [33]:
predict03

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False])

In [34]:
np.sum(predict03)

109

In [35]:
len(predict03)

114

In [36]:
acc=np.sum(predict03)/len(predict03)

In [37]:
acc

0.956140350877193