In [1]:
!conda install scikit-learn -y

Channels:
 - defaults
 - nvidia
 - pytorch
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [2]:
!conda install pandas -y

Channels:
 - defaults
 - nvidia
 - pytorch
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np
import torch
import torch.optim as optim
import torch.nn as nn

In [4]:
data=datasets.load_breast_cancer()

In [5]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
X=data.data

In [7]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
y=data.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [10]:
y=y.reshape(-1,1)

In [11]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [13]:
X_train

array([[1.163e+01, 2.929e+01, 7.487e+01, ..., 6.835e-02, 2.884e-01,
        7.220e-02],
       [1.175e+01, 2.018e+01, 7.610e+01, ..., 7.909e-02, 3.168e-01,
        7.987e-02],
       [1.126e+01, 1.996e+01, 7.372e+01, ..., 9.314e-02, 2.955e-01,
        7.009e-02],
       ...,
       [1.086e+01, 2.148e+01, 6.851e+01, ..., 0.000e+00, 2.458e-01,
        6.592e-02],
       [1.275e+01, 1.670e+01, 8.251e+01, ..., 8.045e-02, 3.071e-01,
        8.557e-02],
       [1.193e+01, 1.091e+01, 7.614e+01, ..., 6.876e-02, 2.460e-01,
        7.262e-02]])

In [14]:
X_test

array([[1.082e+01, 2.421e+01, 6.889e+01, ..., 3.264e-02, 3.059e-01,
        7.626e-02],
       [1.168e+01, 1.617e+01, 7.549e+01, ..., 9.815e-02, 2.804e-01,
        8.024e-02],
       [1.141e+01, 1.492e+01, 7.353e+01, ..., 6.296e-02, 1.811e-01,
        7.427e-02],
       ...,
       [1.245e+01, 1.570e+01, 8.257e+01, ..., 1.741e-01, 3.985e-01,
        1.244e-01],
       [1.380e+01, 1.579e+01, 9.043e+01, ..., 1.383e-01, 2.589e-01,
        1.030e-01],
       [1.381e+01, 2.375e+01, 9.156e+01, ..., 2.013e-01, 4.432e-01,
        1.086e-01]])

In [15]:
y_train

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
    

In [16]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
    

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [18]:
X_train=scaler.transform(X_train)
X_train

array([[-0.70398346,  2.30198757, -0.69981016, ..., -0.68462882,
        -0.00695219, -0.61778829],
       [-0.67026254,  0.20567395, -0.64953936, ..., -0.52249708,
         0.4592448 , -0.19760691],
       [-0.80795629,  0.15504948, -0.74681132, ..., -0.31039737,
         0.10959706, -0.73337925],
       ...,
       [-0.92035935,  0.5048186 , -0.95974699, ..., -1.71644489,
        -0.70624766, -0.96182206],
       [-0.38925489, -0.59511325, -0.387559  , ..., -0.50196643,
         0.30001555,  0.11465304],
       [-0.61968116, -1.92745747, -0.64790454, ..., -0.67843944,
        -0.70296459, -0.59477966]])

In [19]:
X_test=scaler.transform(X_test)
X_test

array([[-0.93159966,  1.13302235, -0.94421618, ..., -1.22370932,
         0.28031708, -0.39537155],
       [-0.68993308, -0.71707222, -0.67447041, ..., -0.23476608,
        -0.13827528, -0.17733741],
       [-0.76580514, -1.0047113 , -0.75457673, ..., -0.76599662,
        -1.76832319, -0.50438862],
       ...,
       [-0.47355718, -0.82522451, -0.38510677, ...,  0.91178008,
         1.8003819 ,  2.24185549],
       [-0.09419685, -0.8045145 , -0.06386408, ...,  0.37134094,
        -0.4912061 ,  1.06951111],
       [-0.09138678,  1.02717117, -0.01768034, ...,  1.32239306,
         2.53414969,  1.37629281]])

In [20]:
w=torch.empty(30,1)
w

tensor([[-5.7678e+17],
        [ 9.1785e-43],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00]])

In [21]:
w=torch.nn.init.xavier_uniform_(w)
w

tensor([[ 0.1267],
        [ 0.4182],
        [ 0.3969],
        [-0.2149],
        [ 0.1965],
        [-0.3313],
        [-0.3077],
        [-0.2629],
        [ 0.0970],
        [ 0.4085],
        [-0.1219],
        [-0.3786],
        [ 0.2298],
        [-0.0241],
        [-0.2893],
        [ 0.4323],
        [ 0.3367],
        [ 0.3167],
        [-0.2908],
        [ 0.2813],
        [-0.1050],
        [-0.0438],
        [ 0.2171],
        [ 0.1528],
        [ 0.4110],
        [-0.0207],
        [-0.3226],
        [ 0.1150],
        [ 0.0252],
        [ 0.1926]])

In [22]:
w=torch.tensor(w,requires_grad=True)
w

C:\Users\User\AppData\Local\Temp\ipykernel_20184\257315764.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w=torch.tensor(w,requires_grad=True)


tensor([[ 0.1267],
        [ 0.4182],
        [ 0.3969],
        [-0.2149],
        [ 0.1965],
        [-0.3313],
        [-0.3077],
        [-0.2629],
        [ 0.0970],
        [ 0.4085],
        [-0.1219],
        [-0.3786],
        [ 0.2298],
        [-0.0241],
        [-0.2893],
        [ 0.4323],
        [ 0.3367],
        [ 0.3167],
        [-0.2908],
        [ 0.2813],
        [-0.1050],
        [-0.0438],
        [ 0.2171],
        [ 0.1528],
        [ 0.4110],
        [-0.0207],
        [-0.3226],
        [ 0.1150],
        [ 0.0252],
        [ 0.1926]], requires_grad=True)

In [23]:
b=torch.tensor([0.0],requires_grad=True,dtype=torch.float)
b

tensor([0.], requires_grad=True)

In [24]:
X_train=torch.FloatTensor(X_train)
X_train

tensor([[-0.7040,  2.3020, -0.6998,  ..., -0.6846, -0.0070, -0.6178],
        [-0.6703,  0.2057, -0.6495,  ..., -0.5225,  0.4592, -0.1976],
        [-0.8080,  0.1550, -0.7468,  ..., -0.3104,  0.1096, -0.7334],
        ...,
        [-0.9204,  0.5048, -0.9597,  ..., -1.7164, -0.7062, -0.9618],
        [-0.3893, -0.5951, -0.3876,  ..., -0.5020,  0.3000,  0.1147],
        [-0.6197, -1.9275, -0.6479,  ..., -0.6784, -0.7030, -0.5948]])

In [25]:
X_test=torch.FloatTensor(X_test)
X_test

tensor([[-0.9316,  1.1330, -0.9442,  ..., -1.2237,  0.2803, -0.3954],
        [-0.6899, -0.7171, -0.6745,  ..., -0.2348, -0.1383, -0.1773],
        [-0.7658, -1.0047, -0.7546,  ..., -0.7660, -1.7683, -0.5044],
        ...,
        [-0.4736, -0.8252, -0.3851,  ...,  0.9118,  1.8004,  2.2419],
        [-0.0942, -0.8045, -0.0639,  ...,  0.3713, -0.4912,  1.0695],
        [-0.0914,  1.0272, -0.0177,  ...,  1.3224,  2.5341,  1.3763]])

In [26]:
y_train=torch.FloatTensor(y_train)
y_train

tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
      

In [27]:
y_test=torch.FloatTensor(y_test)
y_test

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [28]:
torch.matmul(X_train,w)

tensor([[-0.8296],
        [-0.4347],
        [ 0.7735],
        [ 0.9717],
        [ 0.4273],
        [ 0.6892],
        [-1.5399],
        [ 0.2603],
        [ 0.5407],
        [-1.0410],
        [ 2.4380],
        [ 1.9189],
        [ 1.0886],
        [-0.7935],
        [ 1.2563],
        [-1.0629],
        [-1.4907],
        [-0.4824],
        [ 0.7489],
        [-0.2401],
        [ 0.6387],
        [ 0.0513],
        [-2.0204],
        [ 0.3754],
        [ 1.2486],
        [-0.7863],
        [ 0.2133],
        [-0.7446],
        [-0.6082],
        [ 0.1730],
        [-0.6181],
        [ 1.3935],
        [-2.1208],
        [ 1.9209],
        [ 0.1835],
        [ 0.4940],
        [ 0.5330],
        [ 3.2067],
        [ 2.6588],
        [ 0.4442],
        [-0.5411],
        [-0.1878],
        [-0.7271],
        [ 0.8576],
        [-0.7405],
        [-0.4184],
        [ 1.0212],
        [-0.5925],
        [-1.5804],
        [-1.0296],
        [-1.5452],
        [ 0.3620],
        [ 0.

In [29]:
torch.matmul(X_train,w)+b

tensor([[-0.8296],
        [-0.4347],
        [ 0.7735],
        [ 0.9717],
        [ 0.4273],
        [ 0.6892],
        [-1.5399],
        [ 0.2603],
        [ 0.5407],
        [-1.0410],
        [ 2.4380],
        [ 1.9189],
        [ 1.0886],
        [-0.7935],
        [ 1.2563],
        [-1.0629],
        [-1.4907],
        [-0.4824],
        [ 0.7489],
        [-0.2401],
        [ 0.6387],
        [ 0.0513],
        [-2.0204],
        [ 0.3754],
        [ 1.2486],
        [-0.7863],
        [ 0.2133],
        [-0.7446],
        [-0.6082],
        [ 0.1730],
        [-0.6181],
        [ 1.3935],
        [-2.1208],
        [ 1.9209],
        [ 0.1835],
        [ 0.4940],
        [ 0.5330],
        [ 3.2067],
        [ 2.6588],
        [ 0.4442],
        [-0.5411],
        [-0.1878],
        [-0.7271],
        [ 0.8576],
        [-0.7405],
        [-0.4184],
        [ 1.0212],
        [-0.5925],
        [-1.5804],
        [-1.0296],
        [-1.5452],
        [ 0.3620],
        [ 0.

In [30]:
torch.sigmoid(torch.matmul(X_train,w)+b)

tensor([[0.3037],
        [0.3930],
        [0.6843],
        [0.7254],
        [0.6052],
        [0.6658],
        [0.1766],
        [0.5647],
        [0.6320],
        [0.2610],
        [0.9197],
        [0.8720],
        [0.7481],
        [0.3114],
        [0.7784],
        [0.2568],
        [0.1838],
        [0.3817],
        [0.6789],
        [0.4403],
        [0.6544],
        [0.5128],
        [0.1171],
        [0.5928],
        [0.7771],
        [0.3130],
        [0.5531],
        [0.3220],
        [0.3525],
        [0.5431],
        [0.3502],
        [0.8012],
        [0.1071],
        [0.8722],
        [0.5457],
        [0.6210],
        [0.6302],
        [0.9611],
        [0.9345],
        [0.6093],
        [0.3679],
        [0.4532],
        [0.3258],
        [0.7022],
        [0.3229],
        [0.3969],
        [0.7352],
        [0.3561],
        [0.1707],
        [0.2632],
        [0.1758],
        [0.5895],
        [0.6795],
        [0.3909],
        [0.6300],
        [0

In [31]:
hypothesis=torch.sigmoid(torch.matmul(X_train,w)+b)
hypothesis

tensor([[0.3037],
        [0.3930],
        [0.6843],
        [0.7254],
        [0.6052],
        [0.6658],
        [0.1766],
        [0.5647],
        [0.6320],
        [0.2610],
        [0.9197],
        [0.8720],
        [0.7481],
        [0.3114],
        [0.7784],
        [0.2568],
        [0.1838],
        [0.3817],
        [0.6789],
        [0.4403],
        [0.6544],
        [0.5128],
        [0.1171],
        [0.5928],
        [0.7771],
        [0.3130],
        [0.5531],
        [0.3220],
        [0.3525],
        [0.5431],
        [0.3502],
        [0.8012],
        [0.1071],
        [0.8722],
        [0.5457],
        [0.6210],
        [0.6302],
        [0.9611],
        [0.9345],
        [0.6093],
        [0.3679],
        [0.4532],
        [0.3258],
        [0.7022],
        [0.3229],
        [0.3969],
        [0.7352],
        [0.3561],
        [0.1707],
        [0.2632],
        [0.1758],
        [0.5895],
        [0.6795],
        [0.3909],
        [0.6300],
        [0

In [32]:
optimizer=optim.Adam([w,b],lr=0.01)

In [33]:
for i in range(100):
    print("i=",i)
    print("w[:3]=",w[3])
    print("b=",b)
    hypothesis=torch.sigmoid(torch.matmul(X_train,w)+b)
    cost=torch.mean(-y_train*torch.log(hypothesis)-(1-y_train)*torch.log(1-hypothesis))
    print("cost=",cost)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    print("="*100)

i= 0
w[:3]= tensor([-0.2149], grad_fn=<SelectBackward0>)
b= tensor([0.], requires_grad=True)
cost= tensor(1.1792, grad_fn=<MeanBackward0>)
i= 1
w[:3]= tensor([-0.2249], grad_fn=<SelectBackward0>)
b= tensor([0.0100], requires_grad=True)
cost= tensor(1.0769, grad_fn=<MeanBackward0>)
i= 2
w[:3]= tensor([-0.2349], grad_fn=<SelectBackward0>)
b= tensor([0.0200], requires_grad=True)
cost= tensor(0.9804, grad_fn=<MeanBackward0>)
i= 3
w[:3]= tensor([-0.2448], grad_fn=<SelectBackward0>)
b= tensor([0.0300], requires_grad=True)
cost= tensor(0.8903, grad_fn=<MeanBackward0>)
i= 4
w[:3]= tensor([-0.2547], grad_fn=<SelectBackward0>)
b= tensor([0.0399], requires_grad=True)
cost= tensor(0.8070, grad_fn=<MeanBackward0>)
i= 5
w[:3]= tensor([-0.2645], grad_fn=<SelectBackward0>)
b= tensor([0.0499], requires_grad=True)
cost= tensor(0.7308, grad_fn=<MeanBackward0>)
i= 6
w[:3]= tensor([-0.2742], grad_fn=<SelectBackward0>)
b= tensor([0.0598], requires_grad=True)
cost= tensor(0.6618, grad_fn=<MeanBackward0>)
i= 

In [34]:
w

tensor([[-0.2459],
        [-0.1012],
        [ 0.0337],
        [-0.5891],
        [-0.0864],
        [-0.5535],
        [-0.5965],
        [-0.5891],
        [-0.1671],
        [ 0.5490],
        [-0.5063],
        [-0.0158],
        [-0.1238],
        [-0.3997],
        [-0.4047],
        [ 0.3095],
        [ 0.2039],
        [ 0.0674],
        [ 0.2480],
        [ 0.2560],
        [-0.4891],
        [-0.5639],
        [-0.1541],
        [-0.2288],
        [ 0.0294],
        [-0.2870],
        [-0.6162],
        [-0.2248],
        [-0.3530],
        [-0.0622]], requires_grad=True)

In [35]:
b

tensor([0.4678], requires_grad=True)

In [36]:
predict=torch.sigmoid(torch.matmul(X_test,w)+b)

In [37]:
predict

tensor([[9.5416e-01],
        [9.5210e-01],
        [9.9752e-01],
        [7.8084e-01],
        [9.4292e-01],
        [1.9293e-03],
        [9.9646e-01],
        [8.5868e-01],
        [5.7562e-01],
        [7.7984e-01],
        [9.8259e-01],
        [3.7855e-02],
        [9.6396e-01],
        [4.0979e-03],
        [9.9707e-01],
        [9.1707e-01],
        [9.8432e-01],
        [8.8558e-02],
        [9.4006e-01],
        [2.2837e-02],
        [9.8998e-01],
        [9.0529e-01],
        [3.4607e-02],
        [5.8095e-02],
        [1.3689e-01],
        [1.0937e-03],
        [4.1511e-01],
        [9.7367e-01],
        [9.5488e-01],
        [9.5225e-01],
        [6.4784e-01],
        [2.3735e-07],
        [9.7389e-01],
        [9.6487e-01],
        [9.7597e-01],
        [7.2753e-06],
        [5.2842e-02],
        [9.5880e-01],
        [6.7583e-07],
        [4.4671e-05],
        [1.3929e-01],
        [9.9081e-03],
        [9.9699e-01],
        [9.9495e-01],
        [9.4016e-01],
        [9

In [38]:
predict01=torch.where(predict>=0.5,torch.tensor([1.]),torch.tensor([0.]))

In [39]:
predict01

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [40]:
y_test

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
      

In [41]:
predict01.eq(y_test)

tensor([[ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True

In [42]:
acc01=predict01.eq(y_test)

In [43]:
acc01

tensor([[ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [False],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True],
        [ True

In [44]:
acc01.type(torch.DoubleTensor)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [45]:
acc02=acc01.type(torch.DoubleTensor)

In [46]:
acc02

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
      

In [47]:
acc03=torch.mean(acc02)

In [48]:
acc03

tensor(0.9649, dtype=torch.float64)

In [49]:
X_arr=np.array([
    [3.8312,1.6324,3.9907,5.4532,0.8753,1.8759,3.5362,3.1806,0.8990,-0.9087,7.9715,0.1713,8.0943,11.9829,0.2529,1.6661,1.5853,2.3802,-0.4427,0.3207,4.1694,0.9339,4.3981,6.2228,0.1643,1.1448,1.9777,2.2735,-0.4414,-0.5454]
])

In [50]:
X_arr

array([[ 3.8312,  1.6324,  3.9907,  5.4532,  0.8753,  1.8759,  3.5362,
         3.1806,  0.899 , -0.9087,  7.9715,  0.1713,  8.0943, 11.9829,
         0.2529,  1.6661,  1.5853,  2.3802, -0.4427,  0.3207,  4.1694,
         0.9339,  4.3981,  6.2228,  0.1643,  1.1448,  1.9777,  2.2735,
        -0.4414, -0.5454]])

In [51]:
X_arr=scaler.transform(X_arr)

In [52]:
X_arr

array([[  -2.89550594,   -4.06233773,   -3.59668761,   -1.83859567,
          55.15509479,   33.49133696,   44.03682612,   81.7584352 ,
          26.33320183, -137.12646636,   26.62004994,   -1.9743485 ,
           2.55845645,   -0.60362051,   78.452922  ,   91.35330265,
          57.54290283,  406.78260689,  -55.3753488 ,  127.41030549,
          -2.47818987,   -4.04698925,   -3.04821348,   -1.5254927 ,
           1.39484692,    5.5950061 ,    8.25799473,   32.60445959,
         -11.98690146,  -34.45142803]])

In [53]:
X_arr=torch.FloatTensor(X_arr)

In [54]:
X_arr

tensor([[  -2.8955,   -4.0623,   -3.5967,   -1.8386,   55.1551,   33.4913,
           44.0368,   81.7584,   26.3332, -137.1265,   26.6201,   -1.9743,
            2.5585,   -0.6036,   78.4529,   91.3533,   57.5429,  406.7826,
          -55.3753,  127.4103,   -2.4782,   -4.0470,   -3.0482,   -1.5255,
            1.3948,    5.5950,    8.2580,   32.6045,  -11.9869,  -34.4514]])

In [55]:
torch.sigmoid(torch.matmul(X_arr,w)+b)

tensor([[0.]], grad_fn=<SigmoidBackward0>)